server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

# ==

spring:
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  # datasource:
  #   url: jdbc:mysql://localhost:3306/paging_searching?serverTimezone=Asia/Seoul
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   username: root
  #   password: 1234
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      # mode: always # 내장 DB 아닐 때 필요
      schema-locations:
        - classpath:db/table.sql
      data-locations:
        - classpath:db/data.sql

logging:
  level: # TRACE > DEBUG > INFO > WARN > ERROR
    "[com.example.jsmybatis_pagingsearching.web]": debug
# ==

mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.jsmybatis_pagingsearching.domain

myjwt: ${MY_JWT}